# -*- coding: utf-8 -*-
"""SogukRadar kaynak rosteri v2 - 72 kaynak.

kind: oem (ekipman ureticisi) | uretici (celik ureticisi) | dergi | kurum
verified=True: adres gercek bir istekle dogrulandi. False olanlar ilk kosuda
`check` ile denenir; erisilemeyenler raporda KOR NOKTA olarak acikca listelenir.

Kapsam elemesi kind'e gore degisir:
- oem: basligin kapsam kapisinden gecmesi ZORUNLU DEGIL (OEM haberi zaten
  buyuk oranda hat/ekipman haberidir; sert red yine calisir)
- uretici/dergi/kurum: baslik + giris kapsam kapisindan gecmek zorunda
  (ureticiler ve dergiler cok gurultu uretir)
"""

SOURCES = [
    # ---------------- OEM / ekipman ureticileri (32) ----------------
    dict(id="danieli",       publisher="Danieli",                  kind="oem", country="IT",
         url="https://www.danieli.com/en/news.htm", rss=None, verified=True),
    dict(id="tenova",        publisher="Tenova",                   kind="oem", country="IT",
         url="https://www.tenova.com/news", rss=None, verified=True),
    dict(id="primetals",     publisher="Primetals Technologies",   kind="oem", country="GB",
         url="https://www.primetals.com/press-media/news", rss=None, verified=True),
    dict(id="johncockerill", publisher="John Cockerill",           kind="oem", country="BE",
         url="https://johncockerill.com/en/press-and-news/news/", rss=None, verified=True),
    dict(id="andritz",       publisher="Andritz Metals",           kind="oem", country="AT",
         url="https://www.andritz.com/newsroom-en/metals", rss=None, verified=True),
    dict(id="smsgroup",      publisher="SMS group",                kind="oem", country="DE",
         url="https://www.sms-group.com/press-and-media/press-releases", rss=None,
         verified=False, note="bot korumasi; tarayici basliklariyla deneniyor"),
    dict(id="fives",         publisher="Fives Group",              kind="oem", country="FR",
         url="https://www.fivesgroup.com/newspress", rss=None, verified=True),
    dict(id="clecim",        publisher="Clecim",                   kind="oem", country="FR",
         url="https://www.clecim.com/news", rss=None, verified=False),
    dict(id="butechbliss",   publisher="Butech Bliss",             kind="oem", country="US",
         url="https://butechbliss.com/latest-news/", rss=None, verified=True),
    dict(id="herkules",      publisher="Herkules Group",           kind="oem", country="DE",
         url="https://www.herkulesgroup.com/news/", rss=None, verified=True),
    dict(id="achenbach",     publisher="Achenbach Buschhutten",    kind="oem", country="DE",
         url="https://www.achenbach.de/en/company/newsroom/", rss=None, verified=True),
    dict(id="ebner",         publisher="Ebner Industrieofenbau",   kind="oem", country="AT",
         url="https://www.ebner.cc/en/news/", rss=None, verified=False),
    dict(id="nseng",         publisher="Nippon Steel Engineering", kind="oem", country="JP",
         url="https://www.eng.nipponsteel.com/english/whatsnew/", rss=None, verified=False),
    dict(id="abbmetals",     publisher="ABB Metals",               kind="oem", country="CH",
         url="https://www.abb.com/global/en/company/media?filter=Business%3AMetals",
         rss=None, verified=False),
    dict(id="isravision",    publisher="ISRA Vision (Atlas Copco)", kind="oem", country="DE",
         url="https://www.isravision.com/en-en/company/newsroom", rss=None, verified=True,
         note="yuzey muayene (SIS)"),
    dict(id="cognex",        publisher="Cognex",                   kind="oem", country="US",
         url="https://www.cognex.com/en/company/press-releases", rss=None,
         verified=False, note="bot korumasi (429)"),
    dict(id="bronx",         publisher="The Bronx Group",          kind="oem", country="US",
         url="https://thebronxgroup.com/news/", rss=None, verified=True),
    dict(id="delta",         publisher="Delta Steel Technologies", kind="oem", country="US",
         url="https://www.deltasteeltech.com/news/", rss=None, verified=False),
    dict(id="mino",          publisher="Mino SpA",                 kind="oem", country="IT",
         url="https://www.mino.it/news", rss=None, verified=False,
         note="soguk hadde tesisleri"),
    dict(id="secowarwick",   publisher="SECO/WARWICK",             kind="oem", country="PL",
         url="https://www.secowarwick.com/en/news/", rss=None, verified=False,
         note="tavlama firinlari (CAL/BAF)"),
    dict(id="georg",         publisher="Heinrich GEORG",           kind="oem", country="DE",
         url="https://georg.com/en/news", rss=None, verified=False,
         note="trafo sac hatlari - elektrik celigi"),
    dict(id="tmeic",         publisher="TMEIC",                    kind="oem", country="JP",
         url="https://www.tmeic.com/news", rss=None, verified=False,
         note="hadde surucu ve otomasyon"),
    dict(id="bwg",           publisher="BWG Maschinenbau",         kind="oem", country="DE",
         url="https://www.bwg-online.de/en/news", rss=None, verified=False,
         note="serit isleme hatlari"),
    dict(id="ims",           publisher="IMS Messsysteme",          kind="oem", country="DE",
         url="https://www.ims-gmbh.de/en/news", rss=None, verified=False,
         note="kalinlik/duzluk olcum"),
    dict(id="emg",           publisher="EMG Automation",           kind="oem", country="DE",
         url="https://www.emg-automation.com/en/news/", rss=None, verified=False,
         note="serit yonlendirme"),
    dict(id="dumabandzink",  publisher="Duma-Bandzink",            kind="oem", country="DE",
         url="https://www.duma-bandzink.com/en/news", rss=None, verified=False,
         note="galvaniz hatti ekipmani"),
    dict(id="ottojunker",    publisher="Otto Junker",              kind="oem", country="DE",
         url="https://www.otto-junker.com/en/news/", rss=None, verified=False),
    dict(id="braner",        publisher="Braner USA",               kind="oem", country="US",
         url="https://www.braner.com/", rss=None, verified=False, note="dilme hatlari"),
    dict(id="redbud",        publisher="Red Bud Industries",       kind="oem", country="US",
         url="https://www.redbudindustries.com/news/", rss=None, verified=False,
         note="boy kesme hatlari"),
    dict(id="herrvoss",      publisher="Herr-Voss Stamco",         kind="oem", country="US",
         url="https://www.herrvoss.com/news/", rss=None, verified=False,
         note="tension leveling"),
    dict(id="waterbury",     publisher="Waterbury Farrel",         kind="oem", country="CA",
         url="https://www.waterburyfarrel.com/news", rss=None, verified=False),
    dict(id="sistemteknik",  publisher="Sistem Teknik",            kind="oem", country="TR",
         url="https://www.sistemteknik.com/en/news", rss=None, verified=False,
         note="Turk firin ureticisi"),

    # ---------------- Celik ureticileri (19) ----------------
    # Hat yatirimini bazen tedarikci degil uretici duyurur; asil boslugu bunlar kapatir.
    dict(id="arcelormittal", publisher="ArcelorMittal",            kind="uretici", country="LU",
         url="https://corporate.arcelormittal.com/media/press-releases", rss=None, verified=False),
    dict(id="tksteel",       publisher="thyssenkrupp Steel",       kind="uretici", country="DE",
         url="https://www.thyssenkrupp-steel.com/en/newsroom/press-releases/",
         rss=None, verified=False),
    dict(id="tatasteel",     publisher="Tata Steel",               kind="uretici", country="IN",
         url="https://www.tatasteel.com/media/newsroom/press-releases/", rss=None, verified=False),
    dict(id="posco",         publisher="POSCO",                    kind="uretici", country="KR",
         url="https://newsroom.posco.com/en/", rss=None, verified=False),
    dict(id="nipponsteel",   publisher="Nippon Steel",             kind="uretici", country="JP",
         url="https://www.nipponsteel.com/en/news/", rss=None, verified=False),
    dict(id="jfe",           publisher="JFE Steel",                kind="uretici", country="JP",
         url="https://www.jfe-steel.co.jp/en/release/", rss=None, verified=False),
    dict(id="jsw",           publisher="JSW Steel",                kind="uretici", country="IN",
         url="https://www.jswsteel.in/media/press-releases", rss=None, verified=False),
    dict(id="voestalpine",   publisher="voestalpine",              kind="uretici", country="AT",
         url="https://www.voestalpine.com/group/en/media/press-releases/", rss=None, verified=False),
    dict(id="salzgitter",    publisher="Salzgitter AG",            kind="uretici", country="DE",
         url="https://www.salzgitter-ag.com/en/media/press-releases.html", rss=None, verified=False),
    dict(id="ssab",          publisher="SSAB",                     kind="uretici", country="SE",
         url="https://www.ssab.com/en/news", rss=None, verified=False),
    dict(id="ussteel",       publisher="U.S. Steel",               kind="uretici", country="US",
         url="https://www.ussteel.com/press-releases", rss=None, verified=False),
    dict(id="cliffs",        publisher="Cleveland-Cliffs",         kind="uretici", country="US",
         url="https://www.clevelandcliffs.com/news", rss=None, verified=False),
    dict(id="nucor",         publisher="Nucor",                    kind="uretici", country="US",
         url="https://nucor.com/news", rss=None, verified=False),
    dict(id="baowu",         publisher="China Baowu",              kind="uretici", country="CN",
         url="https://www.baowugroup.com/en/press_media", rss=None, verified=False),
    dict(id="hyundaisteel",  publisher="Hyundai Steel",            kind="uretici", country="KR",
         url="https://www.hyundai-steel.com/en/pr/news.hds", rss=None, verified=False),
    dict(id="erdemir",       publisher="Erdemir",                  kind="uretici", country="TR",
         url="https://www.erdemir.com.tr/kurumsal-iletisim/haberler/", rss=None,
         verified=False, lang="tr"),
    dict(id="tosyali",       publisher="Tosyali Holding",          kind="uretici", country="TR",
         url="https://www.tosyaliholding.com.tr/tr/medya/haberler", rss=None,
         verified=False, lang="tr"),
    dict(id="borcelik",      publisher="Borcelik",                 kind="uretici", country="TR",
         url="https://www.borcelik.com/tr/haberler", rss=None, verified=False, lang="tr"),
    dict(id="mmkturkey",     publisher="MMK Metalurji",            kind="uretici", country="TR",
         url="https://www.mmkmetalurji.com.tr/haberler", rss=None, verified=False, lang="tr"),

    # ---------------- Dergi / haber (17) ----------------
    dict(id="steeltimesint", publisher="Steel Times International", kind="dergi", country="GB",
         url="https://www.steeltimesint.com/news", rss=None, verified=True,
         note="sunucu IP'sinden zaman zaman 403"),
    dict(id="steelturk",     publisher="SteelTurk",                kind="dergi", country="TR",
         url="https://www.steelturk.com.tr/global-celik-haberleri/", rss=None,
         verified=True, lang="tr"),
    dict(id="steelradar",    publisher="Steel Radar",              kind="dergi", country="TR",
         url="https://www.steelradar.com/en/", rss=None, verified=True),
    dict(id="metaldunyasi",  publisher="Metal Dunyasi",            kind="dergi", country="TR",
         url="https://metaldunyasi.com.tr/tr/sektorel-haberler/20/demir-elik/",
         rss=None, verified=True, lang="tr"),
    dict(id="steelorbis",    publisher="SteelOrbis",               kind="dergi", country="TR",
         url="https://www.steelorbis.com/steel-news/latest-news/", rss=None, verified=True),
    dict(id="eurometal",     publisher="EUROMETAL",                kind="dergi", country="LU",
         url="https://eurometal.net/news/", rss="https://eurometal.net/feed/", verified=True),
    dict(id="canmaker",      publisher="The Canmaker",             kind="dergi", country="GB",
         url="https://canmaker.com/news/", rss="https://canmaker.com/feed", verified=True),
    dict(id="kallanish",     publisher="Kallanish",                kind="dergi", country="GB",
         url="https://www.kallanish.com/en/news/steel/live", rss=None, verified=True),
    dict(id="gmk",           publisher="GMK Center",               kind="dergi", country="UA",
         url="https://gmk.center/en/news/", rss=None, verified=True),
    dict(id="meps",          publisher="MEPS International",       kind="dergi", country="GB",
         url="https://mepsinternational.com/gb/en/news", rss=None, verified=True),
    dict(id="steelguru",     publisher="SteelGuru",                kind="dergi", country="IN",
         url="https://www.steelguru.com/", rss=None, verified=True),
    dict(id="magnetics",     publisher="Magnetics Magazine",       kind="dergi", country="US",
         url="https://magneticsmag.com/magnetics-news/", rss=None, verified=True),
    dict(id="yieh",          publisher="Yieh Corp",                kind="dergi", country="TW",
         url="https://www.yieh.com/en/News/", rss=None, verified=True),
    dict(id="fastmarkets",   publisher="Fastmarkets",              kind="dergi", country="GB",
         url="https://www.fastmarkets.com/metals-and-mining/steel-and-steel-raw-materials/",
         rss=None, verified=True),
    dict(id="smm",           publisher="SMM (Shanghai Metals)",    kind="dergi", country="CN",
         url="https://news.metal.com/steel", rss=None, verified=False),
    dict(id="bigmint",       publisher="BigMint (SteelMint)",      kind="dergi", country="IN",
         url="https://www.bigmint.co/insights", rss=None, verified=False),
    dict(id="metalminer",    publisher="MetalMiner",               kind="dergi", country="US",
         url="https://agmetalminer.com/", rss=None, verified=False),

    # ---------------- Kurum (4) ----------------
    dict(id="worldsteel",    publisher="worldsteel",               kind="kurum", country="BE",
         url="https://worldsteel.org/media/press-releases/",
         rss="https://worldsteel.org/feed/", verified=True),
    dict(id="aist",          publisher="AIST",                     kind="kurum", country="US",
         url="https://www.aist.org/news-events/", rss=None, verified=False),
    dict(id="eurofer",       publisher="EUROFER",                  kind="kurum", country="BE",
         url="https://www.eurofer.eu/press-releases/", rss=None, verified=False),
    dict(id="tcud",          publisher="TCUD",                     kind="kurum", country="TR",
         url="https://celik.org.tr/haberler/", rss=None, verified=False, lang="tr"),
]

KNOWN_GAPS = [
    ("Redex Group", "sitesinde haber bolumu yok"),
    ("Drever International", "tum adresler bot korumasiyla kapali"),
    ("Sarralle", "haber listesi JavaScript ile yukleniyor"),
    ("Cin yerel OEM'leri (CISDI, MCC, SINOSTEEL)", "yalniz Cince yayin"),
    ("Argus / Platts tam icerik", "odeme duvari"),
    ("LinkedIn duyurulari", "giris zorunlu"),
]


def by_id(sid):
    for s in SOURCES:
        if s["id"] == sid:
            return s
    return None


def active(kinds=None):
    if not kinds:
        return list(SOURCES)
    return [s for s in SOURCES if s["kind"] in kinds]
