# -*- coding: utf-8 -*-
"""SogukRadar kaynak rosteri v2 - 72 kaynak.

kind: oem (ekipman ureticisi) | uretici (celik ureticisi) | dergi | kurum
verified=True: adres gercek bir istekle dogrulandi. False olanlar ilk kosuda
`check` ile denenir; erisilemeyenler raporda KOR NOKTA olarak acikca listelenir.

Kapsam elemesi kind'e gore degisir:
- oem: basligin kapsam kapisinden gecmesi ZORUNLU DEGIL (OEM haberi zaten
  buyuk oranda hat/ekipman haberidir; sert red yine calisir)
- uretici/dergi/kurum: baslik + giris kapsam kapisindan gecmek zorunda
  (ureticiler ve dergiler cok gurultu uretir)
"""

SOURCES = [
    # ---------------- OEM / ekipman ureticileri (32) ----------------
    dict(id="danieli",       publisher="Danieli",                  kind="oem", country="IT",
         url="https://www.danieli.com/en/news.htm", rss=None, verified=True),
    dict(id="tenova",        publisher="Tenova",                   kind="oem", country="IT",
         url="https://www.tenova.com/news", rss=None, verified=True),
    dict(id="primetals",     publisher="Primetals Technologies",   kind="oem", country="GB",
         url="https://www.primetals.com/press-media/news", rss=None, verified=True),
    dict(id="johncockerill", publisher="John Cockerill",           kind="oem", country="BE",
         url="https://johncockerill.com/en/press-and-news/news/", rss=None, verified=True),
    dict(id="andritz",       publisher="Andritz Metals",           kind="oem", country="AT",
         url="https://www.andritz.com/newsroom-en/metals", rss=None, verified=True),
    dict(id="smsgroup",      publisher="SMS group",                kind="oem", country="DE",
         url="https://www.sms-group.com/press-and-media/press-releases", rss=None,
         verified=False, note="bot korumasi; tarayici basliklariyla deneniyor",
         sitemaps=["https://www.sms-group.com/sitemap.xml"],
         robots=["https://www.sms-group.com"]),
    dict(id="fives",         publisher="Fives Group",              kind="oem", country="FR",
         url="https://www.fivesgroup.com/newspress", rss=None, verified=True),
    dict(id="clecim",        publisher="Clecim",                   kind="oem", country="FR",
         url="https://www.clecim.com/news", rss=None, verified=False),
    dict(id="butechbliss",   publisher="Butech Bliss",             kind="oem", country="US",
         url="https://butechbliss.com/latest-news/", rss=None, verified=True),
    dict(id="herkules",      publisher="Herkules Group",           kind="oem", country="DE",
         url="https://www.herkulesgroup.com/news/", rss=None, verified=True),
    dict(id="achenbach",     publisher="Achenbach Buschhutten",    kind="oem", country="DE",
         url="https://www.achenbach.de/en/company/newsroom/", rss=None, verified=True),
    dict(id="ebner",         publisher="Ebner Industrieofenbau",   kind="oem", country="AT",
         url="https://www.ebner.cc/en/news/", rss=None, verified=False),
    dict(id="nseng",         publisher="Nippon Steel Engineering", kind="oem", country="JP",
         url="https://www.eng.nipponsteel.com/english/whatsnew/", rss=None, verified=False),
    dict(id="abbmetals",     publisher="ABB Metals",               kind="oem", country="CH",
         url="https://www.abb.com/global/en/company/media?filter=Business%3AMetals",
         rss=None, verified=False,
         sitemaps=["https://new.abb.com/news/rss"],
         robots=["https://new.abb.com"]),
    dict(id="isravision",    publisher="ISRA Vision (Atlas Copco)", kind="oem", country="DE",
         url="https://www.isravision.com/en-en/company/newsroom", rss=None, verified=True,
         note="yuzey muayene (SIS)"),
    dict(id="cognex",        publisher="Cognex",                   kind="oem", country="US",
         url="https://www.cognex.com/en/company/press-releases", rss=None,
         verified=False, note="bot korumasi (429)",
         sitemaps=["https://www.cognex.com/sitemap.xml"],
         robots=["https://www.cognex.com"]),
    dict(id="bronx",         publisher="The Bronx Group",          kind="oem", country="US",
         url="https://thebronxgroup.com/news/", rss=None, verified=True),
    dict(id="delta",         publisher="Delta Steel Technologies", kind="oem", country="US",
         url="https://www.deltasteeltech.com/news/", rss=None, verified=False),
    dict(id="mino",          publisher="Mino SpA",                 kind="oem", country="IT",
         url="https://www.mino.it/news", rss=None, verified=False,
         note="soguk hadde tesisleri"),
    dict(id="secowarwick",   publisher="SECO/WARWICK",             kind="oem", country="PL",
         url="https://www.secowarwick.com/en/news/", rss=None, verified=False,
         note="tavlama firinlari (CAL/BAF)"),
    dict(id="tmeic",         publisher="TMEIC",                    kind="oem", country="JP",
         url="https://www.tmeic.com/news", rss=None, verified=False,
         note="hadde surucu ve otomasyon"),
    dict(id="ims",           publisher="IMS Messsysteme",          kind="oem", country="DE",
         url="https://www.ims-gmbh.de/en/press-section/", rss=None, verified=False,
         note="kalinlik/duzluk olcum"),
    dict(id="emg",           publisher="EMG Automation",           kind="oem", country="DE",
         url="https://www.emg-automation.com/en/news/", rss=None, verified=False,
         note="serit yonlendirme"),
    dict(id="ottojunker",    publisher="Otto Junker",              kind="oem", country="DE",
         url="https://www.otto-junker.com/en/news/", rss=None, verified=False),
    dict(id="braner",        publisher="Braner USA",               kind="oem", country="US",
         url="https://www.braner.com/", rss=None, verified=False, note="dilme hatlari"),
    dict(id="waterbury",     publisher="Waterbury Farrel",         kind="oem", country="CA",
         url="https://www.waterburyfarrel.com/news", rss=None, verified=False),

    # ---------------- Celik ureticileri (19) ----------------
    # Hat yatirimini bazen tedarikci degil uretici duyurur; asil boslugu bunlar kapatir.
    dict(id="arcelormittal", publisher="ArcelorMittal",            kind="uretici", country="LU",
         url="https://corporate.arcelormittal.com/media/press-releases/", rss=None, verified=False,
         sitemaps=["https://corporate.arcelormittal.com/sitemap.xml"],
         robots=["https://corporate.arcelormittal.com"]),
    dict(id="tksteel",       publisher="thyssenkrupp Steel",       kind="uretici", country="DE",
         url="https://www.thyssenkrupp-steel.com/en/newsroom/press-releases/",
         rss=None, verified=False),
    dict(id="tatasteel",     publisher="Tata Steel",               kind="uretici", country="IN",
         url="https://www.tatasteel.com/media/newsroom/press-releases/", rss=None, verified=False),
    dict(id="posco",         publisher="POSCO",                    kind="uretici", country="KR",
         url="https://newsroom.posco.com/en/", rss=None, verified=False),
    dict(id="nipponsteel",   publisher="Nippon Steel",             kind="uretici", country="JP",
         url="https://www.nipponsteel.com/en/news/", rss=None, verified=False,
         sitemaps=["https://www.nipponsteel.com/en/news/sitemap.xml", "https://www.nipponsteel.com/sitemap.xml"],
         robots=["https://www.nipponsteel.com"]),
    dict(id="jfe",           publisher="JFE Steel",                kind="uretici", country="JP",
         url="https://www.jfe-steel.co.jp/en/release/", rss=None, verified=False),
    dict(id="jsw",           publisher="JSW Steel",                kind="uretici", country="IN",
         url="https://www.jswsteel.in/investors/corporate-announcement-and-press-release/", rss=None, verified=False),
    dict(id="voestalpine",   publisher="voestalpine",              kind="uretici", country="AT",
         url="https://www.voestalpine.com/group/en/media/press-releases/", rss=None, verified=False),
    dict(id="salzgitter",    publisher="Salzgitter AG",            kind="uretici", country="DE",
         url="https://www.salzgitter-ag.com/en/newsroom/press-releases.html", rss=None, verified=False),
    dict(id="ssab",          publisher="SSAB",                     kind="uretici", country="SE",
         url="https://www.ssab.com/en/news", rss=None, verified=False),
    dict(id="ussteel",       publisher="U.S. Steel",               kind="uretici", country="US",
         url="https://www.ussteel.com/media/newsroom", rss=None, verified=False),
    dict(id="cliffs",        publisher="Cleveland-Cliffs",         kind="uretici", country="US",
         url="https://www.clevelandcliffs.com/news", rss=None, verified=False),
    dict(id="nucor",         publisher="Nucor",                    kind="uretici", country="US",
         url="https://nucor.com/news", rss=None, verified=False),
    dict(id="baowu",         publisher="China Baowu",              kind="uretici", country="CN",
         url="https://www.baowugroup.com/en/press_media", rss=None, verified=False,
         sitemaps=["https://www.baowugroup.com/sitemap.xml"],
         robots=["https://www.baowugroup.com"]),
    dict(id="erdemir",       publisher="Erdemir",                  kind="uretici", country="TR",
         url="https://www.erdemir.com.tr/en/corporate/media/press-release", rss=None,
         verified=True),
    dict(id="tosyali",       publisher="Tosyali Holding",          kind="uretici", country="TR",
         url="https://www.tosyaliholding.com.tr/en/media-central/press-releases", rss=None,
         verified=False, lang="tr"),

    # ---------------- Dergi / haber (17) ----------------
    # 2026-08-17 olcumu: 6,5 ayda bulunan 25 kapsam ici haberin 11'i BURADAN
    # cikti - havuzun en verimli tek kaynagi. Ama /news sayfasi bota 403
    # veriyordu, yani en iyi kaynak sisteme HIC girmiyordu. Haber sitemap'i
    # 403 vermiyor ve basligi adresin icinde tasiyor.
    dict(id="steeltimesint", publisher="Steel Times International", kind="dergi", country="GB",
         url="https://www.steeltimesint.com/news", rss=None, verified=True,
         sitemaps=["https://www.steeltimesint.com/sitemaps-1-section-news-1-sitemap.xml",
                   "https://www.steeltimesint.com/sitemap.xml",
                   "https://www.steeltimesint.com/news-sitemap.xml",
                   "https://www.steeltimesint.com/feed",
                   "https://www.steeltimesint.com/rss"],
         robots=["https://www.steeltimesint.com"],
         note="HTML ve sitemap 403 verebiliyor; zincir + robots.txt denenir"),
    dict(id="steelturk",     publisher="SteelTurk",                kind="dergi", country="TR",
         url="https://www.steelturk.com.tr/global-celik-haberleri/", rss=None,
         verified=True, lang="tr"),
    dict(id="steelradar",    publisher="Steel Radar",              kind="dergi", country="TR",
         url="https://www.steelradar.com/en/", rss=None, verified=True),
    dict(id="metaldunyasi",  publisher="Metal Dunyasi",            kind="dergi", country="TR",
         url="https://metaldunyasi.com.tr/tr/sektorel-haberler/20/demir-elik/",
         rss=None, verified=True, lang="tr"),
    # 25 haberin 7'si buradan. Ucretsiz katman sitemap'i ~3 hafta tasiyor ve
    # saat hassasiyetinde lastmod veriyor; uretici tarafi olaylari (Ternium,
    # Tosyali ilk bobin, tk accelis) yalnizca bu kaynakta gorundu.
    dict(id="steelorbis",    publisher="SteelOrbis",               kind="dergi", country="TR",
         url="https://www.steelorbis.com/steel-news/latest-news/", rss=None, verified=True,
         sitemap="https://www.steelorbis.com/sitemap-news-en-free-1.xml"),
    dict(id="eurometal",     publisher="EUROMETAL",                kind="dergi", country="LU",
         url="https://eurometal.net/news/", rss="https://eurometal.net/feed/", verified=True),
    dict(id="canmaker",      publisher="The Canmaker",             kind="dergi", country="GB",
         url="https://canmaker.com/news/", rss="https://canmaker.com/feed", verified=True),
    dict(id="kallanish",     publisher="Kallanish",                kind="dergi", country="GB",
         url="https://www.kallanish.com/en/news/steel/live", rss=None, verified=True),
    # /feed/ sonsuz yonlendirme dongusune giriyor; sitemap saglam.
    dict(id="gmk",           publisher="GMK Center",               kind="dergi", country="UA",
         url="https://gmk.center/en/news/", rss=None, verified=True,
         sitemap="https://gmk.center/news-sitemap50.xml"),
    dict(id="meps",          publisher="MEPS International",       kind="dergi", country="GB",
         url="https://mepsinternational.com/gb/en/news", rss=None, verified=True),
    dict(id="steelguru",     publisher="SteelGuru",                kind="dergi", country="IN",
         url="https://www.steelguru.com/", rss=None, verified=True,
         sitemaps=["https://www.steelguru.com/sitemap.xml", "https://www.steelguru.com/rss", "https://www.steelguru.com/feed"],
         robots=["https://www.steelguru.com"]),
    dict(id="magnetics",     publisher="Magnetics Magazine",       kind="dergi", country="US",
         url="https://magneticsmag.com/magnetics-news/", rss=None, verified=True),
    dict(id="yieh",          publisher="Yieh Corp",                kind="dergi", country="TW",
         url="https://www.yieh.com/en/News/", rss=None, verified=True),
    dict(id="fastmarkets",   publisher="Fastmarkets",              kind="dergi", country="GB",
         url="https://www.fastmarkets.com/metals-and-mining/steel-and-steel-raw-materials/",
         rss=None, verified=True),
    dict(id="smm",           publisher="SMM (Shanghai Metals)",    kind="dergi", country="CN",
         url="https://news.metal.com/en/ferrous-metals", rss=None, verified=False),
    dict(id="bigmint",       publisher="BigMint (SteelMint)",      kind="dergi", country="IN",
         url="https://www.bigmint.co/insights", rss=None, verified=False,
         sitemaps=["https://www.bigmint.co/sitemap.xml"],
         robots=["https://www.bigmint.co"]),
    dict(id="metalminer",    publisher="MetalMiner",               kind="dergi", country="US",
         url="https://agmetalminer.com/articles/", rss=None, verified=False,
         sitemaps=["https://agmetalminer.com/feed/", "https://agmetalminer.com/sitemap.xml"],
         robots=["https://agmetalminer.com"]),

    # ---------------- Kurum (4) ----------------
    dict(id="worldsteel",    publisher="worldsteel",               kind="kurum", country="BE",
         url="https://worldsteel.org/media/press-releases/",
         rss="https://worldsteel.org/feed/", verified=True,
         sitemaps=["https://worldsteel.org/sitemap_index.xml", "https://worldsteel.org/sitemap.xml", "https://worldsteel.org/feed/"],
         robots=["https://worldsteel.org"]),
    dict(id="aist",          publisher="AIST",                     kind="kurum", country="US",
         url="https://www.aist.org/news-events/", rss=None, verified=False,
         sitemaps=["https://www.aist.org/sitemap.xml", "https://www.aist.org/feed"],
         robots=["https://www.aist.org"]),
    dict(id="eurofer",       publisher="EUROFER",                  kind="kurum", country="BE",
         url="https://www.eurofer.eu/press-releases/", rss=None, verified=False),
    dict(id="tcud",          publisher="TCUD",                     kind="kurum", country="TR",
         url="https://celik.org.tr/tr/bilgi-merkezi/basin-bulteni", rss=None, verified=False, lang="tr"),


    # ---------------- v4 EK KAYNAKLAR (2026-08-12 arastirmasi) ----------------
    # Steel Times Int ile ayni altyapi; HTML tarafi 403 veriyordu.
    dict(id="furnacesint",  publisher="Furnaces International", kind="dergi", country="GB",
         url="https://www.furnaces-international.com/", rss=None, verified=True,
         sitemap="https://furnaces-international.com/sitemaps-1-section-news-1-sitemap.xml",
         sitemaps=["https://furnaces-international.com/sitemaps-1-section-news-1-sitemap.xml", "https://furnaces-international.com/sitemap.xml", "https://furnaces-international.com/feed"],
         robots=["https://furnaces-international.com"]),
    dict(id="heattreat",    publisher="Heat Treat Today",      kind="dergi", country="US",
         url="https://www.heattreattoday.com/", rss=None, verified=True),
    dict(id="metalforming", publisher="MetalForming Magazine", kind="dergi", country="US",
         url="https://www.metalformingmagazine.com/", rss=None, verified=True,
         sitemaps=["https://www.metalformingmagazine.com/sitemap.xml", "https://www.metalformingmagazine.com/feed"],
         robots=["https://www.metalformingmagazine.com"]),
    dict(id="pma",          publisher="PMA",                   kind="kurum", country="US",
         url="https://www.pma.org/news/", rss=None, verified=True),
    # CIN KATMANI (2026-08-17). Dunyanin soguk hadde / kaplama hatti
    # projelerinin buyuk kismi Cin'de ve havuz Cince tek satir okumuyordu.
    # Kanit: Mysteel 14 Agustos 2026'da "\u5e7f\u4e1c\u91d1\u6657\u5170 1780mm ... \u5408\u540c\u7b7e\u8ba2"
    # (ekipman sozlesmesi) yayinladi, havuz gormedi.
    # Adres tarihi kodluyor: /a/YYMMDDHH/HASH.html -> pencere elemesi sayfa
    # ACILMADAN yapilir; tarih yine makale sayfasindan dogrulanir.
    dict(id="mysteel",      publisher="Mysteel",               kind="dergi", country="CN",
         url="https://www.mysteel.net/", rss=None, verified=True,
         sitemaps=["https://news.mysteel.com/sitemap_news.xml",
                   "https://news.mysteel.com/sitemap.xml"],
         robots=["https://news.mysteel.com", "https://www.mysteel.com",
                 "https://www.mysteel.net"],
         note="sitemap adresleri 404; robots.txt uzerinden kesfedilir"),
    dict(id="mysteel_fac",  publisher="Mysteel (tesis/proje)", kind="dergi", country="CN",
         url="https://factory.mysteel.com/", rss=None, verified=True, lang="zh",
         note="proje/ekipman kanali - hat sozlesmeleri burada duyurulur"),
    dict(id="mysteel_news", publisher="Mysteel (haber)",       kind="dergi", country="CN",
         url="https://news.mysteel.com/", rss=None, verified=True, lang="zh"),
    dict(id="metallurgprom", publisher="Metallurgprom",        kind="dergi", country="UA",
         url="https://metallurgprom.org/en/news/", rss=None, verified=True),
    dict(id="siderweb",     publisher="Siderweb",              kind="dergi", country="IT",
         url="https://www.siderweb.com/", rss=None, verified=True),
    dict(id="alacero",      publisher="Alacero",               kind="kurum", country="CL",
         url="https://www.alacero.org/en/noticias", rss=None, verified=True),
    dict(id="mesteel",      publisher="MEsteel",               kind="dergi", country="AE",
         url="https://news.mesteel.com/", rss=None, verified=True),
    dict(id="japanmetal",   publisher="Japan Metal Daily",     kind="dergi", country="JP",
         url="https://www.japanmetaldaily.com/subcategory/news", rss=None, verified=True),
    dict(id="wvstahl",      publisher="WV Stahl",              kind="kurum", country="DE",
         url="https://www.wvstahl.de/pressemitteilungen/", rss=None, verified=True),
    dict(id="steelhome",    publisher="SteelHome",             kind="dergi", country="CN",
         url="https://www.steelhome.com/", rss=None, verified=True),
    dict(id="sanayigazete", publisher="Sanayi Gazetesi",       kind="dergi", country="TR",
         url="https://sanayigazetesi.com.tr/", rss=None, verified=True, lang="tr"),
    dict(id="cib",          publisher="Celik Ihracatcilari Birligi", kind="kurum", country="TR",
         url="https://www.cib.org.tr/tr/haberler.html", rss=None, verified=True, lang="tr"),
    dict(id="metalmakina",  publisher="MetalMakina",           kind="dergi", country="TR",
         url="https://www.metalmakina.com/", rss=None, verified=True, lang="tr"),
    dict(id="aisi",         publisher="AISI",                  kind="kurum", country="US",
         url="https://www.steel.org/news/", rss=None, verified=True),
    dict(id="sma",          publisher="Steel Manufacturers Assoc.", kind="kurum", country="US",
         url="https://steelnet.org/news/", rss=None, verified=True),
    dict(id="iza",          publisher="International Zinc Assoc.", kind="kurum", country="US",
         url="https://www.zinc.org/in-the-news/", rss=None, verified=True),
    dict(id="egga",         publisher="Galvanizing Europe",    kind="kurum", country="BE",
         url="https://www.galvanizingeurope.org/", rss=None, verified=True),
    dict(id="arku",         publisher="ARKU",                  kind="oem", country="DE",
         url="https://www.arku.com/en/news/", rss=None, verified=True,
         note="duzeltme (leveling) ve capak alma"),
    dict(id="bradbury",     publisher="Bradbury Group",        kind="oem", country="US",
         url="https://blog.bradburygroup.com/blog/all", rss=None, verified=True,
         note="bobin isleme / roll forming"),
    dict(id="chemetall",    publisher="Chemetall (BASF)",      kind="oem", country="DE",
         url="https://www.chemetall.com/global/en/about-us/press-releases", rss=None,
         verified=True, note="on islem / pasivasyon kimyasi"),
    dict(id="kocks",        publisher="Kocks (SMS)",           kind="oem", country="DE",
         url="https://www.kocks.de/en/news/", rss=None, verified=True,
         sitemaps=["https://www.kocks.de/sitemap.xml"],
         robots=["https://www.kocks.de"]),

    # ---------------- Arama beslemeleri (45) ----------------
    dict(id="gq_hat00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22pickling%20line%22%20OR%20%22pickling%20section%22%20OR%20%22push-pull%20pickling%22%20OR%20PLTCM%29%20steel%20-price%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22pickling%20line%22%20OR%20%22pickling%20section%22%20OR%20%22push-pull%20pickling%22%20OR%20PLTCM%29%20steel%20-price%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22acid%20regeneration%22%20OR%20%22spent%20pickle%20liquor%22%20OR%20%22spray%20roaster%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22acid%20regeneration%22%20OR%20%22spent%20pickle%20liquor%22%20OR%20%22spray%20roaster%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22cold%20rolling%20mill%22%20OR%20%22tandem%20cold%20mill%22%20OR%20%22reversing%20cold%20mill%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22cold%20rolling%20mill%22%20OR%20%22tandem%20cold%20mill%22%20OR%20%22reversing%20cold%20mill%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22continuous%20annealing%22%20OR%20%22annealing%20line%22%20OR%20%22radiant%20tube%22%20OR%20%22batch%20annealing%22%29%20strip%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22continuous%20annealing%22%20OR%20%22annealing%20line%22%20OR%20%22radiant%20tube%22%20OR%20%22batch%20annealing%22%29%20strip%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat04", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22galvanizing%20line%22%20OR%20%22hot-dip%20galvanizing%22%20OR%20galvanneal%20OR%20%22zinc%20coating%20line%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22galvanizing%20line%22%20OR%20%22hot-dip%20galvanizing%22%20OR%20galvanneal%20OR%20%22zinc%20coating%20line%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat05", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22zinc%20pot%22%20OR%20%22air%20knife%22%20OR%20%22gas%20wiping%22%20OR%20%22pot%20roll%22%29%20galvanizing%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22zinc%20pot%22%20OR%20%22air%20knife%22%20OR%20%22gas%20wiping%22%20OR%20%22pot%20roll%22%29%20galvanizing%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat06", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22coil%20coating%22%20OR%20%22colour%20coating%20line%22%20OR%20%22color%20coating%20line%22%20OR%20prepainted%20OR%20PPGI%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22coil%20coating%22%20OR%20%22colour%20coating%20line%22%20OR%20%22color%20coating%20line%22%20OR%20prepainted%20OR%20PPGI%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat07", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28tinplate%20OR%20%22tin%20mill%22%20OR%20%22electrolytic%20tinning%22%20OR%20ECCS%20OR%20%22tin-free%20steel%22%29%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28tinplate%20OR%20%22tin%20mill%22%20OR%20%22electrolytic%20tinning%22%20OR%20ECCS%20OR%20%22tin-free%20steel%22%29%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat08", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22electrical%20steel%22%20OR%20%22silicon%20steel%22%20OR%20CRGO%20OR%20CRNO%20OR%20%22grain-oriented%22%29%20plant%20OR%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22electrical%20steel%22%20OR%20%22silicon%20steel%22%20OR%20CRGO%20OR%20CRNO%20OR%20%22grain-oriented%22%29%20plant%20OR%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat09", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22skin%20pass%22%20OR%20%22temper%20mill%22%20OR%20%22tension%20leveller%22%20OR%20%22tension%20leveler%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22skin%20pass%22%20OR%20%22temper%20mill%22%20OR%20%22tension%20leveller%22%20OR%20%22tension%20leveler%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat10", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22slitting%20line%22%20OR%20%22cut-to-length%22%20OR%20%22blanking%20line%22%20OR%20%22side%20trimmer%22%29%20steel%20coil%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22slitting%20line%22%20OR%20%22cut-to-length%22%20OR%20%22blanking%20line%22%20OR%20%22side%20trimmer%22%29%20steel%20coil%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat11", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22steel%20service%20center%22%20OR%20%22steel%20service%20centre%22%20OR%20%22coil%20processing%20line%22%29%20investment%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22steel%20service%20center%22%20OR%20%22steel%20service%20centre%22%20OR%20%22coil%20processing%20line%22%29%20investment%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat12", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22roll%20shop%22%20OR%20%22roll%20grinding%22%20OR%20%22roll%20texturing%22%20OR%20%22work%20roll%22%29%20mill%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22roll%20shop%22%20OR%20%22roll%20grinding%22%20OR%20%22roll%20texturing%22%20OR%20%22work%20roll%22%29%20mill%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat13", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22surface%20inspection%22%20OR%20%22defect%20detection%22%20OR%20%22strip%20inspection%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22surface%20inspection%22%20OR%20%22defect%20detection%22%20OR%20%22strip%20inspection%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat14", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22thickness%20gauge%22%20OR%20%22flatness%20control%22%20OR%20shapemeter%20OR%20%22shape%20meter%22%29%20rolling%20mill%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22thickness%20gauge%22%20OR%20%22flatness%20control%22%20OR%20shapemeter%20OR%20%22shape%20meter%22%29%20rolling%20mill%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat15", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22strip%20welder%22%20OR%20%22flash%20butt%20welder%22%20OR%20%22mash%20seam%20welder%22%20OR%20%22coil%20joining%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22strip%20welder%22%20OR%20%22flash%20butt%20welder%22%20OR%20%22mash%20seam%20welder%22%20OR%20%22coil%20joining%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat16", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28looper%20OR%20accumulator%20OR%20uncoiler%20OR%20%22payoff%20reel%22%29%20%22processing%20line%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28looper%20OR%20accumulator%20OR%20uncoiler%20OR%20%22payoff%20reel%22%29%20%22processing%20line%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat17", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22coil%20handling%22%20OR%20%22coil%20packaging%22%20OR%20%22coil%20transport%22%20OR%20strapping%29%20steel%20plant%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22coil%20handling%22%20OR%20%22coil%20packaging%22%20OR%20%22coil%20transport%22%20OR%20strapping%29%20steel%20plant%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat18", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22cleaning%20line%22%20OR%20degreasing%20OR%20%22electrolytic%20cleaning%22%29%20strip%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22cleaning%20line%22%20OR%20degreasing%20OR%20%22electrolytic%20cleaning%22%29%20strip%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat19", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22digital%20twin%22%20OR%20%22Level%202%20automation%22%20OR%20%22process%20automation%22%29%20%22rolling%20mill%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22digital%20twin%22%20OR%20%22Level%202%20automation%22%20OR%20%22process%20automation%22%29%20%22rolling%20mill%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22SMS%20group%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22SMS%20group%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Primetals%22%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Primetals%22%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Danieli%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Danieli%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Andritz%22%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Andritz%22%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup04", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22John%20Cockerill%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22John%20Cockerill%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup05", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Tenova%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Tenova%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup06", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Fives%22%20steel%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Fives%22%20steel%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup07", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Clecim%22%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Clecim%22%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup08", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Butech%20Bliss%22%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Butech%20Bliss%22%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup09", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Herkules%22%20roll%20grinding%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Herkules%22%20roll%20grinding%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup10", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22SECO/WARWICK%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22SECO/WARWICK%22%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup11", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22ARKU%22%20leveling%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22ARKU%22%20leveling%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup12", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Primetals%22%20OR%20%22SMS%20group%22%20order%20steel%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Primetals%22%20OR%20%22SMS%20group%22%20order%20steel%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_tr00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22so%C4%9Fuk%20haddehane%22%20OR%20%22so%C4%9Fuk%20hadde%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22so%C4%9Fuk%20haddehane%22%20OR%20%22so%C4%9Fuk%20hadde%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22asitleme%20hatt%C4%B1%22%20OR%20%22tavlama%20hatt%C4%B1%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22asitleme%20hatt%C4%B1%22%20OR%20%22tavlama%20hatt%C4%B1%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22galvaniz%20hatt%C4%B1%22%20OR%20%22galvanizli%20sac%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22galvaniz%20hatt%C4%B1%22%20OR%20%22galvanizli%20sac%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22boyama%20hatt%C4%B1%22%20OR%20%22boyal%C4%B1%20sac%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22boyama%20hatt%C4%B1%22%20OR%20%22boyal%C4%B1%20sac%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr04", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22dilme%20hatt%C4%B1%22%20OR%20%22boy%20kesme%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22dilme%20hatt%C4%B1%22%20OR%20%22boy%20kesme%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr05", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22%C3%A7elik%20servis%20merkezi%22%20OR%20%22sac%20i%C5%9Fleme%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22%C3%A7elik%20servis%20merkezi%22%20OR%20%22sac%20i%C5%9Fleme%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr06", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22yass%C4%B1%20%C3%A7elik%22%20yat%C4%B1r%C4%B1m%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22yass%C4%B1%20%C3%A7elik%22%20yat%C4%B1r%C4%B1m%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr07", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22teneke%22%20OR%20%22elektrik%20%C3%A7eli%C4%9Fi%22%20tesis%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22teneke%22%20OR%20%22elektrik%20%C3%A7eli%C4%9Fi%22%20tesis%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_urun00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22cold%20rolled%20coil%22%20investment%20OR%20expansion%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22cold%20rolled%20coil%22%20investment%20OR%20expansion%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_urun01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22galvanized%20steel%22%20new%20line%20capacity%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22galvanized%20steel%22%20new%20line%20capacity%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_urun02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22press%20hardened%20steel%22%20OR%20AHSS%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22press%20hardened%20steel%22%20OR%20AHSS%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_urun03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=steel%20%22patent%22%20OR%20%22R%26D%22%20rolling%20OR%20coating%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=steel%20%22patent%22%20OR%20%22R%26D%22%20rolling%20OR%20coating%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),

    # ---------------- ELLE BESLEME (2026-08-29) ----------------
    # Bot korumasi yuzunden hem yazilima hem editorun oturumuna kapali
    # yayinlarin (STI, SMS group, ArcelorMittal, BigMint, MetalMiner...)
    # basliklari editor tarafindan ARAMA ile bulunup veri/elle_besleme.json'a
    # yazilir. Dosya TARIH TASIMAZ - tarih her zamanki gibi makale sayfasi
    # acilarak dogrulanir. Kapsam kapisi da degismez.
    dict(id="elle", publisher="Elle besleme", kind="dergi", country="XX",
         url="veri/elle_besleme.json", dosya="veri/elle_besleme.json",
         rss=None, verified=True),

    # ---------------- EK ARAMA KATMANI (2026-08-27) ----------------
    # Uc amac: (1) 403 veren kaynaklarin haberini BASKA yayinlardan
    # yakalamak - siteyi acamiyoruz ama haberi yalniz o yazmiyor,
    # (2) kapsamin daha once sorgulanmamis koseleri (temper, roll shop,
    # serit kaynak, olcum, otomasyon, ECL, EGL, Zn-Al-Mg...),
    # (3) dil katmanlari: TR, ZH, KO, JA, DE, ES. Yassi hat haberinin
    # buyuk kismi Ingilizce yayina hic dusmuyor.
    dict(id="gx_sms_group", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22SMS%20group%22%20%28line%20OR%20mill%20OR%20strip%20OR%20coating%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22SMS%20group%22%20%28line%20OR%20mill%20OR%20strip%20OR%20coating%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_arcelor", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22ArcelorMittal%22%20%28galvanizing%20OR%20%22cold%20rolling%22%20OR%20coating%20OR%20tinplate%20OR%20%22electrical%20steel%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22ArcelorMittal%22%20%28galvanizing%20OR%20%22cold%20rolling%22%20OR%20coating%20OR%20tinplate%20OR%20%22electrical%20steel%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_sti_q", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Steel%20Times%20International%22%20OR%20%28steel%20%22processing%20line%22%20commissioned%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Steel%20Times%20International%22%20OR%20%28steel%20%22processing%20line%22%20commissioned%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_gmk_q", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=GMK%20OR%20%28steel%20plant%20%22cold%20rolling%22%20OR%20galvanizing%20Ukraine%20OR%20Europe%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=GMK%20OR%20%28steel%20plant%20%22cold%20rolling%22%20OR%20galvanizing%20Ukraine%20OR%20Europe%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_bigmint_q", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=India%20steel%20%28%22cold%20rolling%22%20OR%20galvanizing%20OR%20%22colour%20coating%22%20OR%20tinplate%29%20capacity%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=India%20steel%20%28%22cold%20rolling%22%20OR%20galvanizing%20OR%20%22colour%20coating%22%20OR%20tinplate%29%20capacity%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_furnaces_q", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28annealing%20furnace%20OR%20%22radiant%20tube%22%20OR%20%22galvanizing%20furnace%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28annealing%20furnace%20OR%20%22radiant%20tube%22%20OR%20%22galvanizing%20furnace%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_cognex_q", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22surface%20inspection%22%20OR%20%22machine%20vision%22%29%20steel%20strip%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22surface%20inspection%22%20OR%20%22machine%20vision%22%29%20steel%20strip%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_clecim_q", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Clecim%22%20OR%20%22Redex%22%20OR%20%22Achenbach%22%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Clecim%22%20OR%20%22Redex%22%20OR%20%22Achenbach%22%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_eurometal_q", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=europe%20steel%20%28%22service%20center%22%20OR%20%22slitting%20line%22%20OR%20%22cut-to-length%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=europe%20steel%20%28%22service%20center%22%20OR%20%22slitting%20line%22%20OR%20%22cut-to-length%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_temper", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22temper%20mill%22%20OR%20%22skin%20pass%22%20OR%20%22skin-pass%20mill%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22temper%20mill%22%20OR%20%22skin%20pass%22%20OR%20%22skin-pass%20mill%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_ecl", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22cleaning%20line%22%20OR%20%22degreasing%20line%22%20OR%20%22electrolytic%20cleaning%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22cleaning%20line%22%20OR%20%22degreasing%20line%22%20OR%20%22electrolytic%20cleaning%22%29%20steel%20strip%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_rollshop", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22roll%20shop%22%20OR%20%22roll%20grinding%20machine%22%20OR%20%22roll%20texturing%22%29%20steel%20mill%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22roll%20shop%22%20OR%20%22roll%20grinding%20machine%22%20OR%20%22roll%20texturing%22%29%20steel%20mill%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_weld", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22strip%20welder%22%20OR%20%22laser%20welder%22%20OR%20%22coil%20joining%22%29%20steel%20processing%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22strip%20welder%22%20OR%20%22laser%20welder%22%20OR%20%22coil%20joining%22%29%20steel%20processing%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_coilhand", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22coil%20handling%22%20OR%20%22coil%20packaging%22%20OR%20%22strapping%20line%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22coil%20handling%22%20OR%20%22coil%20packaging%22%20OR%20%22strapping%20line%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_gauge", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22thickness%20gauge%22%20OR%20%22flatness%20control%22%20OR%20%22coating%20weight%22%20OR%20shapemeter%29%20strip%20mill%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22thickness%20gauge%22%20OR%20%22flatness%20control%22%20OR%20%22coating%20weight%22%20OR%20shapemeter%29%20strip%20mill%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_auto", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22level%202%22%20OR%20%22process%20automation%22%20OR%20%22digital%20twin%22%29%20%28%22cold%20mill%22%20OR%20%22galvanizing%20line%22%20OR%20%22annealing%20line%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22level%202%22%20OR%20%22process%20automation%22%20OR%20%22digital%20twin%22%29%20%28%22cold%20mill%22%20OR%20%22galvanizing%20line%22%20OR%20%22annealing%20line%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_etl", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22tin%20mill%22%20OR%20tinplate%20OR%20%22electrolytic%20tinning%22%20OR%20%22tin-free%20steel%22%29%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22tin%20mill%22%20OR%20tinplate%20OR%20%22electrolytic%20tinning%22%20OR%20%22tin-free%20steel%22%29%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_ccl", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22colour%20coating%20line%22%20OR%20%22color%20coating%20line%22%20OR%20%22coil%20coating%22%20OR%20prepainted%20OR%20PPGI%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22colour%20coating%20line%22%20OR%20%22color%20coating%20line%22%20OR%20%22coil%20coating%22%20OR%20prepainted%20OR%20PPGI%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_egl", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22electrogalvanizing%22%20OR%20%22electro-galvanizing%22%20OR%20%22EGL%20line%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22electrogalvanizing%22%20OR%20%22electro-galvanizing%22%20OR%20%22EGL%20line%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_znalmg", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22Zn-Al-Mg%22%20OR%20ZAM%20OR%20Magnelis%20OR%20Galvalume%20OR%20Aluzinc%29%20coating%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22Zn-Al-Mg%22%20OR%20ZAM%20OR%20Magnelis%20OR%20Galvalume%20OR%20Aluzinc%29%20coating%20line%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_elec2", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22electrical%20steel%22%20OR%20%22silicon%20steel%22%20OR%20%22grain-oriented%22%29%20%28line%20OR%20plant%20OR%20furnace%29%20investment%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22electrical%20steel%22%20OR%20%22silicon%20steel%22%20OR%20%22grain-oriented%22%29%20%28line%20OR%20plant%20OR%20furnace%29%20investment%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_ssc", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22steel%20service%20center%22%20OR%20%22slitting%20line%22%20OR%20%22cut-to-length%20line%22%20OR%20%22blanking%20line%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22steel%20service%20center%22%20OR%20%22slitting%20line%22%20OR%20%22cut-to-length%20line%22%20OR%20%22blanking%20line%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_arp", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22acid%20regeneration%22%20OR%20%22acid%20regeneration%20plant%22%20OR%20%22pickle%20liquor%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22acid%20regeneration%22%20OR%20%22acid%20regeneration%20plant%22%20OR%20%22pickle%20liquor%22%29%20steel%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_commis", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=steel%20%28%22processing%20line%22%20OR%20%22coating%20line%22%20OR%20%22cold%20mill%22%29%20%28commissioned%20OR%20%22first%20coil%22%20OR%20%22starts%20production%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=steel%20%28%22processing%20line%22%20OR%20%22coating%20line%22%20OR%20%22cold%20mill%22%29%20%28commissioned%20OR%20%22first%20coil%22%20OR%20%22starts%20production%22%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_order", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=steel%20%28%22galvanizing%20line%22%20OR%20%22pickling%20line%22%20OR%20%22annealing%20line%22%20OR%20%22cold%20mill%22%29%20%28order%20OR%20contract%20OR%20awarded%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=steel%20%28%22galvanizing%20line%22%20OR%20%22pickling%20line%22%20OR%20%22annealing%20line%22%20OR%20%22cold%20mill%22%29%20%28order%20OR%20contract%20OR%20awarded%29%20when%3A30d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gx_q_tr1", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=so%C4%9Fuk%20haddehane%20OR%20%22galvaniz%20hatt%C4%B1%22%20OR%20%22tavlama%20hatt%C4%B1%22%20OR%20%22asitleme%20hatt%C4%B1%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=so%C4%9Fuk%20haddehane%20OR%20%22galvaniz%20hatt%C4%B1%22%20OR%20%22tavlama%20hatt%C4%B1%22%20OR%20%22asitleme%20hatt%C4%B1%22%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False),
    dict(id="gx_q_tr2", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22boyama%20hatt%C4%B1%22%20OR%20%22dilme%20hatt%C4%B1%22%20OR%20%22teneke%20hatt%C4%B1%22%20OR%20%22elektrik%20%C3%A7eli%C4%9Fi%22%20yat%C4%B1r%C4%B1m%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22boyama%20hatt%C4%B1%22%20OR%20%22dilme%20hatt%C4%B1%22%20OR%20%22teneke%20hatt%C4%B1%22%20OR%20%22elektrik%20%C3%A7eli%C4%9Fi%22%20yat%C4%B1r%C4%B1m%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False),
    dict(id="gx_q_tr3", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%C3%A7elik%20%22devreye%20ald%C4%B1%22%20OR%20%22ilk%20%C3%BCretim%22%20hat%20yat%C4%B1r%C4%B1m%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%C3%A7elik%20%22devreye%20ald%C4%B1%22%20OR%20%22ilk%20%C3%BCretim%22%20hat%20yat%C4%B1r%C4%B1m%20when%3A30d&hl=tr&gl=TR&ceid=TR:tr", verified=False),
    dict(id="gx_q_zh1", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%E5%86%B7%E8%BD%A7%20OR%20%E9%85%B8%E6%B4%97%20OR%20%E8%BF%9E%E9%80%80%20%E6%9C%BA%E7%BB%84%20%E6%8A%95%E4%BA%A7%20when%3A30d&hl=zh-CN&gl=CN&ceid=CN:zh-Hans",
         rss="https://news.google.com/rss/search?q=%E5%86%B7%E8%BD%A7%20OR%20%E9%85%B8%E6%B4%97%20OR%20%E8%BF%9E%E9%80%80%20%E6%9C%BA%E7%BB%84%20%E6%8A%95%E4%BA%A7%20when%3A30d&hl=zh-CN&gl=CN&ceid=CN:zh-Hans", verified=False),
    dict(id="gx_q_zh2", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%E9%95%80%E9%94%8C%20OR%20%E5%BD%A9%E6%B6%82%20OR%20%E9%95%80%E9%94%A1%20%E6%9C%BA%E7%BB%84%20%E5%90%88%E5%90%8C%20OR%20%E6%8A%95%E4%BA%A7%20when%3A30d&hl=zh-CN&gl=CN&ceid=CN:zh-Hans",
         rss="https://news.google.com/rss/search?q=%E9%95%80%E9%94%8C%20OR%20%E5%BD%A9%E6%B6%82%20OR%20%E9%95%80%E9%94%A1%20%E6%9C%BA%E7%BB%84%20%E5%90%88%E5%90%8C%20OR%20%E6%8A%95%E4%BA%A7%20when%3A30d&hl=zh-CN&gl=CN&ceid=CN:zh-Hans", verified=False),
    dict(id="gx_q_zh3", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%E7%A1%85%E9%92%A2%20OR%20%E6%97%A0%E5%8F%96%E5%90%91%20%E6%9C%BA%E7%BB%84%20OR%20%E9%80%80%E7%81%AB%E7%82%89%20%E6%8A%95%E4%BA%A7%20when%3A30d&hl=zh-CN&gl=CN&ceid=CN:zh-Hans",
         rss="https://news.google.com/rss/search?q=%E7%A1%85%E9%92%A2%20OR%20%E6%97%A0%E5%8F%96%E5%90%91%20%E6%9C%BA%E7%BB%84%20OR%20%E9%80%80%E7%81%AB%E7%82%89%20%E6%8A%95%E4%BA%A7%20when%3A30d&hl=zh-CN&gl=CN&ceid=CN:zh-Hans", verified=False),
    dict(id="gx_q_ko1", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%EB%83%89%EC%97%B0%20OR%20%EB%8F%84%EA%B8%88%20OR%20%EC%86%8C%EB%91%94%20%EC%84%A4%EB%B9%84%20%EC%A4%80%EA%B3%B5%20OR%20%EC%B0%A9%EA%B3%B5%20when%3A30d&hl=ko&gl=KR&ceid=KR:ko",
         rss="https://news.google.com/rss/search?q=%EB%83%89%EC%97%B0%20OR%20%EB%8F%84%EA%B8%88%20OR%20%EC%86%8C%EB%91%94%20%EC%84%A4%EB%B9%84%20%EC%A4%80%EA%B3%B5%20OR%20%EC%B0%A9%EA%B3%B5%20when%3A30d&hl=ko&gl=KR&ceid=KR:ko", verified=False),
    dict(id="gx_q_ja1", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%E5%86%B7%E5%BB%B6%20OR%20%E6%BA%B6%E8%9E%8D%E4%BA%9C%E9%89%9B%E3%82%81%E3%81%A3%E3%81%8D%20OR%20%E9%80%A3%E7%B6%9A%E7%84%BC%E9%88%8D%20%E3%83%A9%E3%82%A4%E3%83%B3%20%E7%A8%BC%E5%83%8D%20when%3A30d&hl=ja&gl=JP&ceid=JP:ja",
         rss="https://news.google.com/rss/search?q=%E5%86%B7%E5%BB%B6%20OR%20%E6%BA%B6%E8%9E%8D%E4%BA%9C%E9%89%9B%E3%82%81%E3%81%A3%E3%81%8D%20OR%20%E9%80%A3%E7%B6%9A%E7%84%BC%E9%88%8D%20%E3%83%A9%E3%82%A4%E3%83%B3%20%E7%A8%BC%E5%83%8D%20when%3A30d&hl=ja&gl=JP&ceid=JP:ja", verified=False),
    dict(id="gx_q_de1", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Kaltwalzwerk%22%20OR%20%22Verzinkungsanlage%22%20OR%20%22Beizlinie%22%20OR%20%22Gluehlinie%22%20Investition%20when%3A30d&hl=de&gl=DE&ceid=DE:de",
         rss="https://news.google.com/rss/search?q=%22Kaltwalzwerk%22%20OR%20%22Verzinkungsanlage%22%20OR%20%22Beizlinie%22%20OR%20%22Gluehlinie%22%20Investition%20when%3A30d&hl=de&gl=DE&ceid=DE:de", verified=False),
    dict(id="gx_q_es1", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22linea%20de%20galvanizado%22%20OR%20%22laminacion%20en%20frio%22%20OR%20%22linea%20de%20decapado%22%20acero%20when%3A30d&hl=es&gl=ES&ceid=ES:es",
         rss="https://news.google.com/rss/search?q=%22linea%20de%20galvanizado%22%20OR%20%22laminacion%20en%20frio%22%20OR%20%22linea%20de%20decapado%22%20acero%20when%3A30d&hl=es&gl=ES&ceid=ES:es", verified=False),
]

KNOWN_GAPS = [
    ("Borcelik / MMK Metalurji / Hyundai Steel", "haber sayfalari JavaScript ile yukleniyor"),
    ("GEORG / BWG / Duma-Bandzink / Red Bud / Herr-Voss", "bot korumasi veya robots engeli"),
    ("Sistem Teknik", "haber sayfasi 2024'ten beri guncellenmiyor"),
    ("Redex Group", "sitesinde haber bolumu yok"),
    ("Drever International", "tum adresler bot korumasiyla kapali"),
    ("Sarralle", "haber listesi JavaScript ile yukleniyor"),
    ("Cin yerel OEM'leri (CISDI, MCC, SINOSTEEL)", "yalniz Cince yayin"),
    ("Argus / Platts tam icerik", "odeme duvari"),
    ("LinkedIn duyurulari", "giris zorunlu"),
]


def by_id(sid):
    for s in SOURCES:
        if s["id"] == sid:
            return s
    return None


def active(kinds=None):
    if not kinds:
        return list(SOURCES)
    return [s for s in SOURCES if s["kind"] in kinds]
