# -*- coding: utf-8 -*-
"""SogukRadar kaynak rosteri v2 - 72 kaynak.

kind: oem (ekipman ureticisi) | uretici (celik ureticisi) | dergi | kurum
verified=True: adres gercek bir istekle dogrulandi. False olanlar ilk kosuda
`check` ile denenir; erisilemeyenler raporda KOR NOKTA olarak acikca listelenir.

Kapsam elemesi kind'e gore degisir:
- oem: basligin kapsam kapisinden gecmesi ZORUNLU DEGIL (OEM haberi zaten
  buyuk oranda hat/ekipman haberidir; sert red yine calisir)
- uretici/dergi/kurum: baslik + giris kapsam kapisindan gecmek zorunda
  (ureticiler ve dergiler cok gurultu uretir)
"""

SOURCES = [
    # ---------------- OEM / ekipman ureticileri (32) ----------------
    dict(id="danieli",       publisher="Danieli",                  kind="oem", country="IT",
         url="https://www.danieli.com/en/news.htm", rss=None, verified=True),
    dict(id="tenova",        publisher="Tenova",                   kind="oem", country="IT",
         url="https://www.tenova.com/news", rss=None, verified=True),
    dict(id="primetals",     publisher="Primetals Technologies",   kind="oem", country="GB",
         url="https://www.primetals.com/press-media/news", rss=None, verified=True),
    dict(id="johncockerill", publisher="John Cockerill",           kind="oem", country="BE",
         url="https://johncockerill.com/en/press-and-news/news/", rss=None, verified=True),
    dict(id="andritz",       publisher="Andritz Metals",           kind="oem", country="AT",
         url="https://www.andritz.com/newsroom-en/metals", rss=None, verified=True),
    dict(id="smsgroup",      publisher="SMS group",                kind="oem", country="DE",
         url="https://www.sms-group.com/press-and-media/press-releases", rss=None,
         verified=False, note="bot korumasi; tarayici basliklariyla deneniyor"),
    dict(id="fives",         publisher="Fives Group",              kind="oem", country="FR",
         url="https://www.fivesgroup.com/newspress", rss=None, verified=True),
    dict(id="clecim",        publisher="Clecim",                   kind="oem", country="FR",
         url="https://www.clecim.com/news", rss=None, verified=False),
    dict(id="butechbliss",   publisher="Butech Bliss",             kind="oem", country="US",
         url="https://butechbliss.com/latest-news/", rss=None, verified=True),
    dict(id="herkules",      publisher="Herkules Group",           kind="oem", country="DE",
         url="https://www.herkulesgroup.com/news/", rss=None, verified=True),
    dict(id="achenbach",     publisher="Achenbach Buschhutten",    kind="oem", country="DE",
         url="https://www.achenbach.de/en/company/newsroom/", rss=None, verified=True),
    dict(id="ebner",         publisher="Ebner Industrieofenbau",   kind="oem", country="AT",
         url="https://www.ebner.cc/en/news/", rss=None, verified=False),
    dict(id="nseng",         publisher="Nippon Steel Engineering", kind="oem", country="JP",
         url="https://www.eng.nipponsteel.com/english/whatsnew/", rss=None, verified=False),
    dict(id="abbmetals",     publisher="ABB Metals",               kind="oem", country="CH",
         url="https://www.abb.com/global/en/company/media?filter=Business%3AMetals",
         rss=None, verified=False),
    dict(id="isravision",    publisher="ISRA Vision (Atlas Copco)", kind="oem", country="DE",
         url="https://www.isravision.com/en-en/company/newsroom", rss=None, verified=True,
         note="yuzey muayene (SIS)"),
    dict(id="cognex",        publisher="Cognex",                   kind="oem", country="US",
         url="https://www.cognex.com/en/company/press-releases", rss=None,
         verified=False, note="bot korumasi (429)"),
    dict(id="bronx",         publisher="The Bronx Group",          kind="oem", country="US",
         url="https://thebronxgroup.com/news/", rss=None, verified=True),
    dict(id="delta",         publisher="Delta Steel Technologies", kind="oem", country="US",
         url="https://www.deltasteeltech.com/news/", rss=None, verified=False),
    dict(id="mino",          publisher="Mino SpA",                 kind="oem", country="IT",
         url="https://www.mino.it/news", rss=None, verified=False,
         note="soguk hadde tesisleri"),
    dict(id="secowarwick",   publisher="SECO/WARWICK",             kind="oem", country="PL",
         url="https://www.secowarwick.com/en/news/", rss=None, verified=False,
         note="tavlama firinlari (CAL/BAF)"),
    dict(id="tmeic",         publisher="TMEIC",                    kind="oem", country="JP",
         url="https://www.tmeic.com/news", rss=None, verified=False,
         note="hadde surucu ve otomasyon"),
    dict(id="ims",           publisher="IMS Messsysteme",          kind="oem", country="DE",
         url="https://www.ims-gmbh.de/en/press-section/", rss=None, verified=False,
         note="kalinlik/duzluk olcum"),
    dict(id="emg",           publisher="EMG Automation",           kind="oem", country="DE",
         url="https://www.emg-automation.com/en/news/", rss=None, verified=False,
         note="serit yonlendirme"),
    dict(id="ottojunker",    publisher="Otto Junker",              kind="oem", country="DE",
         url="https://www.otto-junker.com/en/news/", rss=None, verified=False),
    dict(id="braner",        publisher="Braner USA",               kind="oem", country="US",
         url="https://www.braner.com/", rss=None, verified=False, note="dilme hatlari"),
    dict(id="waterbury",     publisher="Waterbury Farrel",         kind="oem", country="CA",
         url="https://www.waterburyfarrel.com/news", rss=None, verified=False),

    # ---------------- Celik ureticileri (19) ----------------
    # Hat yatirimini bazen tedarikci degil uretici duyurur; asil boslugu bunlar kapatir.
    dict(id="arcelormittal", publisher="ArcelorMittal",            kind="uretici", country="LU",
         url="https://corporate.arcelormittal.com/media/press-releases/", rss=None, verified=False),
    dict(id="tksteel",       publisher="thyssenkrupp Steel",       kind="uretici", country="DE",
         url="https://www.thyssenkrupp-steel.com/en/newsroom/press-releases/",
         rss=None, verified=False),
    dict(id="tatasteel",     publisher="Tata Steel",               kind="uretici", country="IN",
         url="https://www.tatasteel.com/media/newsroom/press-releases/", rss=None, verified=False),
    dict(id="posco",         publisher="POSCO",                    kind="uretici", country="KR",
         url="https://newsroom.posco.com/en/", rss=None, verified=False),
    dict(id="nipponsteel",   publisher="Nippon Steel",             kind="uretici", country="JP",
         url="https://www.nipponsteel.com/en/news/", rss=None, verified=False),
    dict(id="jfe",           publisher="JFE Steel",                kind="uretici", country="JP",
         url="https://www.jfe-steel.co.jp/en/release/", rss=None, verified=False),
    dict(id="jsw",           publisher="JSW Steel",                kind="uretici", country="IN",
         url="https://www.jswsteel.in/investors/corporate-announcement-and-press-release/", rss=None, verified=False),
    dict(id="voestalpine",   publisher="voestalpine",              kind="uretici", country="AT",
         url="https://www.voestalpine.com/group/en/media/press-releases/", rss=None, verified=False),
    dict(id="salzgitter",    publisher="Salzgitter AG",            kind="uretici", country="DE",
         url="https://www.salzgitter-ag.com/en/newsroom/press-releases.html", rss=None, verified=False),
    dict(id="ssab",          publisher="SSAB",                     kind="uretici", country="SE",
         url="https://www.ssab.com/en/news", rss=None, verified=False),
    dict(id="ussteel",       publisher="U.S. Steel",               kind="uretici", country="US",
         url="https://www.ussteel.com/media/newsroom", rss=None, verified=False),
    dict(id="cliffs",        publisher="Cleveland-Cliffs",         kind="uretici", country="US",
         url="https://www.clevelandcliffs.com/news", rss=None, verified=False),
    dict(id="nucor",         publisher="Nucor",                    kind="uretici", country="US",
         url="https://nucor.com/news", rss=None, verified=False),
    dict(id="baowu",         publisher="China Baowu",              kind="uretici", country="CN",
         url="https://www.baowugroup.com/en/press_media", rss=None, verified=False),
    dict(id="erdemir",       publisher="Erdemir",                  kind="uretici", country="TR",
         url="https://www.erdemir.com.tr/en/corporate/media/press-release", rss=None,
         verified=True),
    dict(id="tosyali",       publisher="Tosyali Holding",          kind="uretici", country="TR",
         url="https://www.tosyaliholding.com.tr/en/media-central/press-releases", rss=None,
         verified=False, lang="tr"),

    # ---------------- Dergi / haber (17) ----------------
    dict(id="steeltimesint", publisher="Steel Times International", kind="dergi", country="GB",
         url="https://www.steeltimesint.com/news", rss=None, verified=True,
         note="sunucu IP'sinden zaman zaman 403"),
    dict(id="steelturk",     publisher="SteelTurk",                kind="dergi", country="TR",
         url="https://www.steelturk.com.tr/global-celik-haberleri/", rss=None,
         verified=True, lang="tr"),
    dict(id="steelradar",    publisher="Steel Radar",              kind="dergi", country="TR",
         url="https://www.steelradar.com/en/", rss=None, verified=True),
    dict(id="metaldunyasi",  publisher="Metal Dunyasi",            kind="dergi", country="TR",
         url="https://metaldunyasi.com.tr/tr/sektorel-haberler/20/demir-elik/",
         rss=None, verified=True, lang="tr"),
    dict(id="steelorbis",    publisher="SteelOrbis",               kind="dergi", country="TR",
         url="https://www.steelorbis.com/steel-news/latest-news/", rss=None, verified=True),
    dict(id="eurometal",     publisher="EUROMETAL",                kind="dergi", country="LU",
         url="https://eurometal.net/news/", rss="https://eurometal.net/feed/", verified=True),
    dict(id="canmaker",      publisher="The Canmaker",             kind="dergi", country="GB",
         url="https://canmaker.com/news/", rss="https://canmaker.com/feed", verified=True),
    dict(id="kallanish",     publisher="Kallanish",                kind="dergi", country="GB",
         url="https://www.kallanish.com/en/news/steel/live", rss=None, verified=True),
    dict(id="gmk",           publisher="GMK Center",               kind="dergi", country="UA",
         url="https://gmk.center/en/news/", rss=None, verified=True),
    dict(id="meps",          publisher="MEPS International",       kind="dergi", country="GB",
         url="https://mepsinternational.com/gb/en/news", rss=None, verified=True),
    dict(id="steelguru",     publisher="SteelGuru",                kind="dergi", country="IN",
         url="https://www.steelguru.com/", rss=None, verified=True),
    dict(id="magnetics",     publisher="Magnetics Magazine",       kind="dergi", country="US",
         url="https://magneticsmag.com/magnetics-news/", rss=None, verified=True),
    dict(id="yieh",          publisher="Yieh Corp",                kind="dergi", country="TW",
         url="https://www.yieh.com/en/News/", rss=None, verified=True),
    dict(id="fastmarkets",   publisher="Fastmarkets",              kind="dergi", country="GB",
         url="https://www.fastmarkets.com/metals-and-mining/steel-and-steel-raw-materials/",
         rss=None, verified=True),
    dict(id="smm",           publisher="SMM (Shanghai Metals)",    kind="dergi", country="CN",
         url="https://news.metal.com/en/ferrous-metals", rss=None, verified=False),
    dict(id="bigmint",       publisher="BigMint (SteelMint)",      kind="dergi", country="IN",
         url="https://www.bigmint.co/insights", rss=None, verified=False),
    dict(id="metalminer",    publisher="MetalMiner",               kind="dergi", country="US",
         url="https://agmetalminer.com/articles/", rss=None, verified=False),

    # ---------------- Kurum (4) ----------------
    dict(id="worldsteel",    publisher="worldsteel",               kind="kurum", country="BE",
         url="https://worldsteel.org/media/press-releases/",
         rss="https://worldsteel.org/feed/", verified=True),
    dict(id="aist",          publisher="AIST",                     kind="kurum", country="US",
         url="https://www.aist.org/news-events/", rss=None, verified=False),
    dict(id="eurofer",       publisher="EUROFER",                  kind="kurum", country="BE",
         url="https://www.eurofer.eu/press-releases/", rss=None, verified=False),
    dict(id="tcud",          publisher="TCUD",                     kind="kurum", country="TR",
         url="https://celik.org.tr/tr/bilgi-merkezi/basin-bulteni", rss=None, verified=False, lang="tr"),


    # ---------------- v4 EK KAYNAKLAR (2026-08-12 arastirmasi) ----------------
    dict(id="furnacesint",  publisher="Furnaces International", kind="dergi", country="GB",
         url="https://www.furnaces-international.com/", rss=None, verified=True),
    dict(id="heattreat",    publisher="Heat Treat Today",      kind="dergi", country="US",
         url="https://www.heattreattoday.com/", rss=None, verified=True),
    dict(id="metalforming", publisher="MetalForming Magazine", kind="dergi", country="US",
         url="https://www.metalformingmagazine.com/news/", rss=None, verified=True),
    dict(id="pma",          publisher="PMA",                   kind="kurum", country="US",
         url="https://www.pma.org/news/", rss=None, verified=True),
    dict(id="mysteel",      publisher="Mysteel",               kind="dergi", country="CN",
         url="https://www.mysteel.net/", rss=None, verified=True),
    dict(id="metallurgprom", publisher="Metallurgprom",        kind="dergi", country="UA",
         url="https://metallurgprom.org/en/news/", rss=None, verified=True),
    dict(id="siderweb",     publisher="Siderweb",              kind="dergi", country="IT",
         url="https://www.siderweb.com/", rss=None, verified=True),
    dict(id="alacero",      publisher="Alacero",               kind="kurum", country="CL",
         url="https://www.alacero.org/en/noticias", rss=None, verified=True),
    dict(id="mesteel",      publisher="MEsteel",               kind="dergi", country="AE",
         url="https://news.mesteel.com/", rss=None, verified=True),
    dict(id="japanmetal",   publisher="Japan Metal Daily",     kind="dergi", country="JP",
         url="https://www.japanmetaldaily.com/subcategory/news", rss=None, verified=True),
    dict(id="wvstahl",      publisher="WV Stahl",              kind="kurum", country="DE",
         url="https://www.wvstahl.de/pressemitteilungen/", rss=None, verified=True),
    dict(id="steelhome",    publisher="SteelHome",             kind="dergi", country="CN",
         url="https://www.steelhome.com/", rss=None, verified=True),
    dict(id="sanayigazete", publisher="Sanayi Gazetesi",       kind="dergi", country="TR",
         url="https://sanayigazetesi.com.tr/", rss=None, verified=True, lang="tr"),
    dict(id="cib",          publisher="Celik Ihracatcilari Birligi", kind="kurum", country="TR",
         url="https://www.cib.org.tr/tr/haberler.html", rss=None, verified=True, lang="tr"),
    dict(id="metalmakina",  publisher="MetalMakina",           kind="dergi", country="TR",
         url="https://www.metalmakina.com/", rss=None, verified=True, lang="tr"),
    dict(id="aisi",         publisher="AISI",                  kind="kurum", country="US",
         url="https://www.steel.org/news/", rss=None, verified=True),
    dict(id="sma",          publisher="Steel Manufacturers Assoc.", kind="kurum", country="US",
         url="https://steelnet.org/news/", rss=None, verified=True),
    dict(id="iza",          publisher="International Zinc Assoc.", kind="kurum", country="US",
         url="https://www.zinc.org/in-the-news/", rss=None, verified=True),
    dict(id="egga",         publisher="Galvanizing Europe",    kind="kurum", country="BE",
         url="https://www.galvanizingeurope.org/", rss=None, verified=True),
    dict(id="arku",         publisher="ARKU",                  kind="oem", country="DE",
         url="https://www.arku.com/en/news/", rss=None, verified=True,
         note="duzeltme (leveling) ve capak alma"),
    dict(id="bradbury",     publisher="Bradbury Group",        kind="oem", country="US",
         url="https://blog.bradburygroup.com/blog/all", rss=None, verified=True,
         note="bobin isleme / roll forming"),
    dict(id="chemetall",    publisher="Chemetall (BASF)",      kind="oem", country="DE",
         url="https://www.chemetall.com/global/en/about-us/press-releases", rss=None,
         verified=True, note="on islem / pasivasyon kimyasi"),
    dict(id="kocks",        publisher="Kocks (SMS)",           kind="oem", country="DE",
         url="https://www.kocks.de/en/news/", rss=None, verified=True),

    # ---------------- Arama beslemeleri (45) ----------------
    dict(id="gq_hat00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22pickling%20line%22%20OR%20%22pickling%20section%22%20OR%20%22push-pull%20pickling%22%20OR%20PLTCM%29%20steel%20-price%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22pickling%20line%22%20OR%20%22pickling%20section%22%20OR%20%22push-pull%20pickling%22%20OR%20PLTCM%29%20steel%20-price%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22acid%20regeneration%22%20OR%20%22spent%20pickle%20liquor%22%20OR%20%22spray%20roaster%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22acid%20regeneration%22%20OR%20%22spent%20pickle%20liquor%22%20OR%20%22spray%20roaster%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22cold%20rolling%20mill%22%20OR%20%22tandem%20cold%20mill%22%20OR%20%22reversing%20cold%20mill%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22cold%20rolling%20mill%22%20OR%20%22tandem%20cold%20mill%22%20OR%20%22reversing%20cold%20mill%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22continuous%20annealing%22%20OR%20%22annealing%20line%22%20OR%20%22radiant%20tube%22%20OR%20%22batch%20annealing%22%29%20strip%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22continuous%20annealing%22%20OR%20%22annealing%20line%22%20OR%20%22radiant%20tube%22%20OR%20%22batch%20annealing%22%29%20strip%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat04", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22galvanizing%20line%22%20OR%20%22hot-dip%20galvanizing%22%20OR%20galvanneal%20OR%20%22zinc%20coating%20line%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22galvanizing%20line%22%20OR%20%22hot-dip%20galvanizing%22%20OR%20galvanneal%20OR%20%22zinc%20coating%20line%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat05", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22zinc%20pot%22%20OR%20%22air%20knife%22%20OR%20%22gas%20wiping%22%20OR%20%22pot%20roll%22%29%20galvanizing%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22zinc%20pot%22%20OR%20%22air%20knife%22%20OR%20%22gas%20wiping%22%20OR%20%22pot%20roll%22%29%20galvanizing%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat06", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22coil%20coating%22%20OR%20%22colour%20coating%20line%22%20OR%20%22color%20coating%20line%22%20OR%20prepainted%20OR%20PPGI%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22coil%20coating%22%20OR%20%22colour%20coating%20line%22%20OR%20%22color%20coating%20line%22%20OR%20prepainted%20OR%20PPGI%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat07", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28tinplate%20OR%20%22tin%20mill%22%20OR%20%22electrolytic%20tinning%22%20OR%20ECCS%20OR%20%22tin-free%20steel%22%29%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28tinplate%20OR%20%22tin%20mill%22%20OR%20%22electrolytic%20tinning%22%20OR%20ECCS%20OR%20%22tin-free%20steel%22%29%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat08", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22electrical%20steel%22%20OR%20%22silicon%20steel%22%20OR%20CRGO%20OR%20CRNO%20OR%20%22grain-oriented%22%29%20plant%20OR%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22electrical%20steel%22%20OR%20%22silicon%20steel%22%20OR%20CRGO%20OR%20CRNO%20OR%20%22grain-oriented%22%29%20plant%20OR%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat09", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22skin%20pass%22%20OR%20%22temper%20mill%22%20OR%20%22tension%20leveller%22%20OR%20%22tension%20leveler%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22skin%20pass%22%20OR%20%22temper%20mill%22%20OR%20%22tension%20leveller%22%20OR%20%22tension%20leveler%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat10", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22slitting%20line%22%20OR%20%22cut-to-length%22%20OR%20%22blanking%20line%22%20OR%20%22side%20trimmer%22%29%20steel%20coil%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22slitting%20line%22%20OR%20%22cut-to-length%22%20OR%20%22blanking%20line%22%20OR%20%22side%20trimmer%22%29%20steel%20coil%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat11", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22steel%20service%20center%22%20OR%20%22steel%20service%20centre%22%20OR%20%22coil%20processing%20line%22%29%20investment%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22steel%20service%20center%22%20OR%20%22steel%20service%20centre%22%20OR%20%22coil%20processing%20line%22%29%20investment%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat12", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22roll%20shop%22%20OR%20%22roll%20grinding%22%20OR%20%22roll%20texturing%22%20OR%20%22work%20roll%22%29%20mill%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22roll%20shop%22%20OR%20%22roll%20grinding%22%20OR%20%22roll%20texturing%22%20OR%20%22work%20roll%22%29%20mill%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat13", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22surface%20inspection%22%20OR%20%22defect%20detection%22%20OR%20%22strip%20inspection%22%29%20steel%20strip%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22surface%20inspection%22%20OR%20%22defect%20detection%22%20OR%20%22strip%20inspection%22%29%20steel%20strip%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat14", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22thickness%20gauge%22%20OR%20%22flatness%20control%22%20OR%20shapemeter%20OR%20%22shape%20meter%22%29%20rolling%20mill%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22thickness%20gauge%22%20OR%20%22flatness%20control%22%20OR%20shapemeter%20OR%20%22shape%20meter%22%29%20rolling%20mill%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat15", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22strip%20welder%22%20OR%20%22flash%20butt%20welder%22%20OR%20%22mash%20seam%20welder%22%20OR%20%22coil%20joining%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22strip%20welder%22%20OR%20%22flash%20butt%20welder%22%20OR%20%22mash%20seam%20welder%22%20OR%20%22coil%20joining%22%29%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat16", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28looper%20OR%20accumulator%20OR%20uncoiler%20OR%20%22payoff%20reel%22%29%20%22processing%20line%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28looper%20OR%20accumulator%20OR%20uncoiler%20OR%20%22payoff%20reel%22%29%20%22processing%20line%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat17", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22coil%20handling%22%20OR%20%22coil%20packaging%22%20OR%20%22coil%20transport%22%20OR%20strapping%29%20steel%20plant%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22coil%20handling%22%20OR%20%22coil%20packaging%22%20OR%20%22coil%20transport%22%20OR%20strapping%29%20steel%20plant%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat18", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22cleaning%20line%22%20OR%20degreasing%20OR%20%22electrolytic%20cleaning%22%29%20strip%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22cleaning%20line%22%20OR%20degreasing%20OR%20%22electrolytic%20cleaning%22%29%20strip%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_hat19", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%28%22digital%20twin%22%20OR%20%22Level%202%20automation%22%20OR%20%22process%20automation%22%29%20%22rolling%20mill%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%28%22digital%20twin%22%20OR%20%22Level%202%20automation%22%20OR%20%22process%20automation%22%29%20%22rolling%20mill%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22SMS%20group%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22SMS%20group%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Primetals%22%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Primetals%22%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Danieli%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Danieli%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Andritz%22%20steel%20strip%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Andritz%22%20steel%20strip%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup04", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22John%20Cockerill%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22John%20Cockerill%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup05", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Tenova%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Tenova%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup06", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Fives%22%20steel%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Fives%22%20steel%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup07", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Clecim%22%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Clecim%22%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup08", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Butech%20Bliss%22%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Butech%20Bliss%22%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup09", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Herkules%22%20roll%20grinding%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Herkules%22%20roll%20grinding%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup10", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22SECO/WARWICK%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22SECO/WARWICK%22%20steel%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup11", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22ARKU%22%20leveling%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22ARKU%22%20leveling%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_sup12", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22Primetals%22%20OR%20%22SMS%20group%22%20order%20steel%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22Primetals%22%20OR%20%22SMS%20group%22%20order%20steel%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_tr00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22so%C4%9Fuk%20haddehane%22%20OR%20%22so%C4%9Fuk%20hadde%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22so%C4%9Fuk%20haddehane%22%20OR%20%22so%C4%9Fuk%20hadde%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22asitleme%20hatt%C4%B1%22%20OR%20%22tavlama%20hatt%C4%B1%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22asitleme%20hatt%C4%B1%22%20OR%20%22tavlama%20hatt%C4%B1%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22galvaniz%20hatt%C4%B1%22%20OR%20%22galvanizli%20sac%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22galvaniz%20hatt%C4%B1%22%20OR%20%22galvanizli%20sac%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22boyama%20hatt%C4%B1%22%20OR%20%22boyal%C4%B1%20sac%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22boyama%20hatt%C4%B1%22%20OR%20%22boyal%C4%B1%20sac%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr04", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22dilme%20hatt%C4%B1%22%20OR%20%22boy%20kesme%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22dilme%20hatt%C4%B1%22%20OR%20%22boy%20kesme%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr05", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22%C3%A7elik%20servis%20merkezi%22%20OR%20%22sac%20i%C5%9Fleme%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22%C3%A7elik%20servis%20merkezi%22%20OR%20%22sac%20i%C5%9Fleme%22%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr06", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22yass%C4%B1%20%C3%A7elik%22%20yat%C4%B1r%C4%B1m%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22yass%C4%B1%20%C3%A7elik%22%20yat%C4%B1r%C4%B1m%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_tr07", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22teneke%22%20OR%20%22elektrik%20%C3%A7eli%C4%9Fi%22%20tesis%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr",
         rss="https://news.google.com/rss/search?q=%22teneke%22%20OR%20%22elektrik%20%C3%A7eli%C4%9Fi%22%20tesis%20when%3A7d&hl=tr&gl=TR&ceid=TR:tr", verified=False, lang="tr"),
    dict(id="gq_urun00", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22cold%20rolled%20coil%22%20investment%20OR%20expansion%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22cold%20rolled%20coil%22%20investment%20OR%20expansion%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_urun01", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22galvanized%20steel%22%20new%20line%20capacity%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22galvanized%20steel%22%20new%20line%20capacity%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_urun02", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=%22press%20hardened%20steel%22%20OR%20AHSS%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=%22press%20hardened%20steel%22%20OR%20AHSS%20line%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
    dict(id="gq_urun03", publisher="Google News", kind="arama", country="XX",
         url="https://news.google.com/rss/search?q=steel%20%22patent%22%20OR%20%22R%26D%22%20rolling%20OR%20coating%20when%3A7d&hl=en-US&gl=US&ceid=US:en",
         rss="https://news.google.com/rss/search?q=steel%20%22patent%22%20OR%20%22R%26D%22%20rolling%20OR%20coating%20when%3A7d&hl=en-US&gl=US&ceid=US:en", verified=False),
]

KNOWN_GAPS = [
    ("Borcelik / MMK Metalurji / Hyundai Steel", "haber sayfalari JavaScript ile yukleniyor"),
    ("GEORG / BWG / Duma-Bandzink / Red Bud / Herr-Voss", "bot korumasi veya robots engeli"),
    ("Sistem Teknik", "haber sayfasi 2024'ten beri guncellenmiyor"),
    ("Redex Group", "sitesinde haber bolumu yok"),
    ("Drever International", "tum adresler bot korumasiyla kapali"),
    ("Sarralle", "haber listesi JavaScript ile yukleniyor"),
    ("Cin yerel OEM'leri (CISDI, MCC, SINOSTEEL)", "yalniz Cince yayin"),
    ("Argus / Platts tam icerik", "odeme duvari"),
    ("LinkedIn duyurulari", "giris zorunlu"),
]


def by_id(sid):
    for s in SOURCES:
        if s["id"] == sid:
            return s
    return None


def active(kinds=None):
    if not kinds:
        return list(SOURCES)
    return [s for s in SOURCES if s["kind"] in kinds]
